name: cothrom

###
### Networks
###

networks:
  ingress:
    driver: bridge
  frontend:
    driver: bridge
  backend:
    driver: bridge
  database:
    driver: bridge

###
### Definitions
###

x-op-app-network: &app-network
  networks:
    - database
    - frontend
    - backend
x-op-app-restart-policy: &app_restart_policy
  restart: unless-stopped
x-op-db-restart-policy: &db_restart_policy
  restart: always
x-op-healthcheck-postgres-policy: &post_health_policy
  healthcheck:
    interval: 10s
    retries: 10
    test: ['CMD-SHELL', 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"']
    timeout: 2s
x-op-postgres-image: &post-image
  image: postgres:17-bookworm
x-op-postgres-network: &db-network
  networks:
    - database

###
### Include
###

include:
  - path: ./docker/data.yml
  - path: ./docker/documents.yml
  - path: ./docker/draw.yml
  # - path: ./docker/files.yml
  - path: ./docker/home.yml

###
### Services
###

services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-cothrom-tunnel
    hostname: cloudflare-cothrom-tunnel
    restart: unless-stopped
    command: tunnel run
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/build/cloudflare/hosts:/etc/hosts
    environment:
      - 'TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}'
    networks:
      - ingress
      - frontend
    healthcheck:
      test: ['CMD', 'cloudflared', '--version']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
