###
### Definitions
###

x-op-app-restart-policy: &app_restart_policy
  restart: unless-stopped
x-op-db-restart-policy: &db_restart_policy
  restart: always
x-op-healthcheck-postgres-policy: &post_health_policy
  healthcheck:
    interval: 10s
    retries: 10
    test: ['CMD-SHELL', 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"']
    timeout: 2s
x-op-postgres-image: &post-image
  image: postgres:17-bookworm
x-op-postgres-network: &db-network
  networks:
    - database
x-op-postgres-labels: &postgres-labels
  labels:
    - io.cothrom.role="database"
    - io.cothrom.stack="datastorage"
    - io.cothrom.data="true"
    - io.cothrom.data.class="database"
    - io.cothrom.db.engine="postgres"
    - io.cothrom.db.backup.command="pg_dump -U $$POSTGRES_USER -d $$POSTGRES_DB"
    - io.cothrom.backup.policy="weekly"

###
### Services
###

services:
  nocodb_data:
    <<: [*post_health_policy, *db_restart_policy, *post-image, *db-network, *postgres-labels]
    container_name: data_nocodb_data
    environment:
      POSTGRES_DB: nocodb_data
      POSTGRES_PASSWORD: ${DATA_DATA_NOCODB_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DATA_DATA_NOCODB_POSTGRES_USER}
    volumes:
      - data_nocodb_data:/var/lib/postgresql/data

  data_nocodb_fineopinion_db:
    <<: [*post_health_policy, *db_restart_policy, *post-image, *db-network, *postgres-labels]
    container_name: data_nocodb_fineopinion_db
    environment:
      POSTGRES_DB: fineopinion_db
      POSTGRES_PASSWORD: ${DATA_FINEOPINION_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DATA_FINEOPINION_POSTGRES_USER}
    volumes:
      - data_nocodb_fineopinion_db:/var/lib/postgresql/data

  data_nocodb_awesome_db:
    <<: [*post_health_policy, *db_restart_policy, *post-image, *db-network, *postgres-labels]
    container_name: data_nocodb_awesome_db
    environment:
      POSTGRES_DB: awesome_db
      POSTGRES_PASSWORD: ${DATA_AWESOME_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DATA_AWESOME_POSTGRES_USER}
    volumes:
      - data_nocodb_awesome_db:/var/lib/postgresql/data

volumes:
  data_nocodb_data:
  data_nocodb_assdisaster_db:
  data_nocodb_fineopinion_db:
  data_nocodb_awesome_db:
  data_nocodb_nia_cr_db:
  data_nocodb_nia_cdn_db:
  data_nocodb_nia_vcasod_db:
  data_nocodb_cothom_tracking_db:
  data_nocodb_electronoise_db:
  data_nocodb_ontime_db:
  data_nocodb_nia_inquiries_db:
